# Generated by Django 5.2.6 on 2025-09-17 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('sportswear', 'Sportswear'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('others', 'Others')], default='others', max_length=30)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('gold', 'Gold'), ('purple', 'Purple'), ('pink', 'Pink')], default='white', max_length=20)),
                ('size', models.CharField(choices=[('s', 'S/38'), ('m', 'M/39'), ('l', 'L/40'), ('xl', 'XL/41'), ('xxl', 'XXL/42')], max_length=10)),
            ],
        ),
    ]
